export const CRDT_WEBSOCKET_CLOSE_POLICY = 1008;
export const CRDT_WEBSOCKET_CLOSE_UNSUPPORTED = 1003;
export const CRDT_WEBSOCKET_CLOSE_TOO_LARGE = 1009;
export const CRDT_WEBSOCKET_CLOSE_BACKPRESSURE = 1009;
export const CRDT_WEBSOCKET_CLOSE_HEARTBEAT_TIMEOUT = 4000;
export const CRDT_WEBSOCKET_DEFAULT_MAX_FRAME_BYTES = 1024 * 1024;
